#!/usr/bin/env tsx
/**
 * Write docs/reference/blocks.md from the blocks barrel's JSDoc.
 *
 *   npm run blocks:catalog
 *
 * The barrel (`interface/src/lib/components/v6/blocks/index.ts`) is the
 * source: one JSDoc paragraph above each export, grouped under
 * `// ---- Section ----` comments. This turns it into the catalog an agent
 * reads to choose a control, so the paragraph is written once, beside the
 * export it describes, and the markdown cannot drift from it. The output
 * is committed (issue #7): rerun this after editing the barrel.
 *
 * Parsed with the TypeScript compiler rather than a regex, so a comment
 * attaches to the statement it actually leads. An export with no JSDoc
 * paragraph fails the run: a block the catalog cannot describe is not in
 * the kit.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import ts from 'typescript';

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const BARREL = join(REPO_ROOT, 'interface/src/lib/components/v6/blocks/index.ts');
const OUT = join(REPO_ROOT, 'docs/reference/blocks.md');
const LIB = 'interface/src/lib';

interface Block {
	name: string;
	source: string;
	doc: string;
}

interface Section {
	title: string;
	blocks: Block[];
}

/** `$lib/x/y.svelte` → `interface/src/lib/x/y.svelte`; a bare TS module gains `.ts`. */
function sourcePath(specifier: string): string {
	const path = specifier.replace(/^\$lib\//, `${LIB}/`);
	return /\.(svelte|ts|js)$/.test(path) ? path : `${path}.ts`;
}

/** A JSDoc block's paragraphs: the leading ` * ` of each line taken off, lines joined, blank lines kept as breaks. */
function jsdocParagraphs(raw: string): string[] {
	return raw
		.replace(/^\/\*\*/, '')
		.replace(/\*\/$/, '')
		.split('\n')
		.map((line) => line.replace(/^\s*\* ?/, '').trim())
		.join('\n')
		.split(/\n{2,}/)
		.map((p) => p.replace(/\n/g, ' ').trim())
		.filter(Boolean);
}

function parse(text: string): { intro: string; sections: Section[] } {
	const file = ts.createSourceFile(BARREL, text, ts.ScriptTarget.Latest, true);
	const sections: Section[] = [];
	let intro = '';
	for (const [i, stmt] of file.statements.entries()) {
		const comments = ts.getLeadingCommentRanges(text, stmt.pos) ?? [];
		let pieces = comments.map((c) => text.slice(c.pos, c.end));
		// The file's own header is the first statement's first JSDoc. Its
		// first paragraph introduces the catalog; the rest is for editors.
		if (i === 0 && pieces[0]?.startsWith('/**')) {
			intro = jsdocParagraphs(pieces[0])[0] ?? '';
			pieces = pieces.slice(1);
		}
		for (const piece of pieces) {
			const heading = piece.match(/^\/\/\s*-+\s*(.+?)\s*-+\s*$/);
			if (heading) sections.push({ title: heading[1], blocks: [] });
		}
		if (!ts.isExportDeclaration(stmt) || !stmt.exportClause || !ts.isNamedExports(stmt.exportClause)) {
			throw new Error(`blocks barrel: only \`export { … } from '…'\` statements belong here (line ${file.getLineAndCharacterOfPosition(stmt.getStart()).line + 1})`);
		}
		const specifier = (stmt.moduleSpecifier as ts.StringLiteral).text;
		const doc = pieces.filter((p) => p.startsWith('/**')).at(-1);
		for (const el of stmt.exportClause.elements) {
			const name = el.name.text;
			if (!doc) {
				throw new Error(`blocks barrel: \`${name}\` has no JSDoc paragraph`);
			}
			if (!sections.length) throw new Error(`blocks barrel: \`${name}\` sits above every \`// ---- Section ----\``);
			sections.at(-1)!.blocks.push({ name, source: sourcePath(specifier), doc: jsdocParagraphs(doc).join('\n\n') });
		}
	}
	return { intro, sections };
}

function render({ intro, sections }: { intro: string; sections: Section[] }): string {
	const barrel = relative(REPO_ROOT, BARREL);
	const lines: string[] = [
		'# Blocks',
		'',
		`<!-- Generated by scripts/generate-blocks-catalog.ts from ${barrel}. Do not edit: edit the barrel's JSDoc and run \`npm run blocks:catalog\`. -->`,
		'',
		intro,
		'',
		`Import from \`$lib/components/v6/blocks\`.`,
		''
	];
	for (const section of sections) {
		if (!section.blocks.length) continue;
		lines.push(`## ${section.title}`, '');
		for (const block of section.blocks) {
			lines.push(`### ${block.name}`, '', `\`${block.source}\``, '', block.doc, '');
		}
	}
	return lines.join('\n');
}

const parsed = parse(readFileSync(BARREL, 'utf8'));
writeFileSync(OUT, render(parsed));
const count = parsed.sections.reduce((n, s) => n + s.blocks.length, 0);
console.log(`blocks: ${count} blocks → ${relative(REPO_ROOT, OUT)}`);
