/**
 * Hands the page the WebSocket shared secret.
 *
 * The bridge gates `ws://…:8081` behind an HMAC challenge (see
 * `interface/bridge/utils/wsSecret.js`), which means the browser needs
 * the secret to answer. The secret lives in a machine-local file that
 * only server-side code can read, so this route is the bridge between
 * the two — both processes run on the same machine and share the file.
 *
 * **What this is worth, stated plainly.** Anything that can reach this
 * route can obtain the secret, and this route is served on the same
 * LAN as the WebSocket. So the gate raises the bar from "anything that
 * can reach port 8081" to "anything that can load the app" — it stops
 * stray clients, stale tabs from another machine and port scanners,
 * not a determined attacker already on the network. Closing that gap
 * needs per-device pairing (a code shown on the Mac, typed on the iPad,
 * kept in localStorage). That is a real option and deliberately not the
 * default, because a cleared browser cache would then lock a performer
 * out mid-session.
 *
 * Never cached: the secret can be regenerated by deleting the file, and
 * a client holding a stale copy would fail the challenge with no way to
 * recover short of a hard reload.
 */

import { error, json, type RequestHandler } from '@sveltejs/kit';
import { createHmac } from 'node:crypto';
import { existsSync, readFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const SECRET_ENV_VAR = 'LOOPING_WS_SECRET';
const SECRET_FILENAME = join('config', '.ws-secret');

/**
 * Walk up for the repo root.
 *
 * `import.meta.url` resolves differently under `vite dev` and a built
 * server, so this walks rather than assuming a fixed depth — the same
 * hazard `config_loader.py` documents on the Python side.
 *
 * The walk is unbounded (it stops at the filesystem root) and starts
 * from both the module's own directory and the process working
 * directory. A bounded walk is what broke this before: the built
 * endpoint lands eight directories deep in
 * `.svelte-kit/output/server/entries/endpoints/api/ws-auth/`, one level
 * further from the repo root than an eight-step climb could reach, so
 * `npm run ipad` served a 503 while `npm run dev` — five levels deep in
 * `src/routes/` — was fine. Any fixed budget is a fresh version of that
 * bug the next time the output layout moves.
 */
function findSecretFile(): string | null {
	const starts = [dirname(fileURLToPath(import.meta.url)), process.cwd()];
	for (const start of starts) {
		let current = start;
		for (;;) {
			const candidate = join(current, SECRET_FILENAME);
			if (existsSync(candidate)) return candidate;
			const parent = resolve(current, '..');
			if (parent === current) break;
			current = parent;
		}
	}
	return null;
}

/** Resolve the secret, or null when it cannot be found. */
function resolveSecret(): string | null {
	const fromEnv = process.env[SECRET_ENV_VAR];
	if (fromEnv && fromEnv.trim()) return fromEnv.trim();

	const file = findSecretFile();
	if (!file) return null;

	const secret = readFileSync(file, 'utf8').trim();
	return secret || null;
}

/**
 * `GET /api/ws-auth?salt=<hex>` → `{ proof }`.
 *
 * The proof is HMAC-SHA256(secret, salt), hex — byte-identical to what
 * `interface/bridge/utils/wsSecret.js` computes, because it is the same
 * three lines of `node:crypto`.
 *
 * **Why the server does this and not the page.** The page used to
 * compute it with `crypto.subtle`, which only exists in a *secure
 * context*. Browsers grant that to `https://` and to `http://localhost`
 * but not to a bare IP — so the iPad, which reaches this rig at
 * `http://169.254.216.140:8889` over USB-C or `http://10.43.156.117:8889`
 * over WiFi, could never answer the challenge. It connected, stayed
 * silent, and the bridge (correctly) told it nothing, which surfaced as
 * "No tracks in session" against a healthy Live set.
 *
 * A salt-less request still returns `{ secret }` so an older cached
 * page keeps working, but nothing in this tree asks for it any more —
 * the raw secret no longer needs to reach a browser at all.
 */
export const GET: RequestHandler = async ({ url }) => {
	let secret: string | null;
	try {
		secret = resolveSecret();
	} catch (e) {
		throw error(500, `Could not read the WebSocket secret: ${(e as Error).message}`);
	}

	if (!secret) {
		// The bridge generates this on first run, so "missing" means the
		// bridge has never started — the UI has nothing to connect to
		// either way, and saying so beats a silent auth failure.
		throw error(503, 'WebSocket secret not available — has the bridge started?');
	}

	const salt = url.searchParams.get('salt');
	if (salt !== null) {
		// The bridge's salt is hex from `crypto.randomBytes`. Rejecting
		// anything else keeps this from being a general-purpose HMAC
		// oracle over caller-chosen input.
		if (!/^[0-9a-f]{16,128}$/.test(salt)) {
			throw error(400, 'salt must be 16-128 lowercase hex characters');
		}
		const proof = createHmac('sha256', secret).update(salt).digest('hex');
		return json({ proof }, { headers: { 'cache-control': 'no-store' } });
	}

	return json({ secret }, { headers: { 'cache-control': 'no-store' } });
};
